domain_path: H:\EGRE429\lab2\platform_lab2\export\platform_lab2\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
