
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xfir.h"

/*
* The configuration table for devices
*/

XFir_Config XFir_ConfigTable[XPAR_XFIR_NUM_INSTANCES] =
{
	{
		XPAR_FIR_LEFT_DEVICE_ID,
		XPAR_FIR_LEFT_S_AXI_FIR_IO_BASEADDR
	},
	{
		XPAR_FIR_RIGHT_DEVICE_ID,
		XPAR_FIR_RIGHT_S_AXI_FIR_IO_BASEADDR
	}
};


